<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TasksTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('tasks')->delete();

        \DB::table('tasks')->insert([
            0 => [
                'id' => 1,
                'title' => 'fsdafsafsafsa',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-09-28',
                'project_id' => 1,
                'created_at' => '2025-09-28 14:18:54',
                'updated_at' => '2025-09-28 15:46:05',
                'created_by' => 1,
            ],
            1 => [
                'id' => 2,
                'title' => 'this is my first',
                'description' => null,
                'type' => 'Medium',
                'status' => 'completed',
                'due_to' => '2025-09-28',
                'project_id' => 1,
                'created_at' => '2025-09-28 14:40:31',
                'updated_at' => '2025-09-28 15:13:04',
                'created_by' => 1,
            ],
            2 => [
                'id' => 3,
                'title' => 'this is my first task',
                'description' => null,
                'type' => 'Medium',
                'status' => 'completed',
                'due_to' => '2025-09-29',
                'project_id' => 2,
                'created_at' => '2025-09-29 09:35:26',
                'updated_at' => '2025-09-29 09:39:22',
                'created_by' => 4,
            ],
            3 => [
                'id' => 4,
                'title' => 'shat afasklfsaf sadfkasjfsal sdkfjas flas',
                'description' => null,
                'type' => 'Urgent',
                'status' => 'completed',
                'due_to' => '2025-09-26',
                'project_id' => 2,
                'created_at' => '2025-09-30 08:52:11',
                'updated_at' => '2025-09-30 08:53:11',
                'created_by' => 4,
            ],
            4 => [
                'id' => 5,
                'title' => 'this is the task importen for the laravel',
                'description' => null,
                'type' => 'High',
                'status' => 'completed',
                'due_to' => '2025-10-22',
                'project_id' => 2,
                'created_at' => '2025-10-04 14:17:37',
                'updated_at' => '2025-10-04 14:27:17',
                'created_by' => 1,
            ],
            5 => [
                'id' => 6,
                'title' => 'sdgsdgfsdgsdgds',
                'description' => null,
                'type' => 'High',
                'status' => 'Pending',
                'due_to' => '2025-10-23',
                'project_id' => 2,
                'created_at' => '2025-10-04 14:36:26',
                'updated_at' => '2025-10-04 14:36:26',
                'created_by' => 1,
            ],
            6 => [
                'id' => 7,
                'title' => 'this is the test',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-04',
                'project_id' => 1,
                'created_at' => '2025-10-04 15:34:34',
                'updated_at' => '2025-10-04 15:34:34',
                'created_by' => 1,
            ],
            7 => [
                'id' => 8,
                'title' => 'this is the another event task',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-04',
                'project_id' => 1,
                'created_at' => '2025-10-04 15:41:01',
                'updated_at' => '2025-10-04 15:41:01',
                'created_by' => 1,
            ],
            8 => [
                'id' => 9,
                'title' => 'fsafasddfsafsaf',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-04',
                'project_id' => 1,
                'created_at' => '2025-10-04 15:42:44',
                'updated_at' => '2025-10-04 15:42:44',
                'created_by' => 1,
            ],
            9 => [
                'id' => 10,
                'title' => 'fsafdsafsaf',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-04',
                'project_id' => 1,
                'created_at' => '2025-10-04 15:44:43',
                'updated_at' => '2025-10-04 15:44:43',
                'created_by' => 1,
            ],
            10 => [
                'id' => 11,
                'title' => 'fasdfdsafdsafa',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-04',
                'project_id' => 1,
                'created_at' => '2025-10-04 15:46:35',
                'updated_at' => '2025-10-04 15:46:35',
                'created_by' => 1,
            ],
            11 => [
                'id' => 12,
                'title' => 'fsafdasfasfdas',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-04',
                'project_id' => 1,
                'created_at' => '2025-10-04 17:06:28',
                'updated_at' => '2025-10-04 17:06:28',
                'created_by' => 1,
            ],
            12 => [
                'id' => 13,
                'title' => 'this is just for test',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-05',
                'project_id' => 2,
                'created_at' => '2025-10-05 08:42:00',
                'updated_at' => '2025-10-05 08:42:00',
                'created_by' => 1,
            ],
            13 => [
                'id' => 14,
                'title' => 'this sjust for another tes',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-05',
                'project_id' => 2,
                'created_at' => '2025-10-05 08:46:03',
                'updated_at' => '2025-10-05 08:46:03',
                'created_by' => 1,
            ],
            14 => [
                'id' => 15,
                'title' => 'gsdgfds',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-05',
                'project_id' => 2,
                'created_at' => '2025-10-05 08:47:35',
                'updated_at' => '2025-10-05 08:47:35',
                'created_by' => 1,
            ],
            15 => [
                'id' => 16,
                'title' => 'the problem fhtis',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-05',
                'project_id' => 2,
                'created_at' => '2025-10-05 08:49:27',
                'updated_at' => '2025-10-05 08:49:27',
                'created_by' => 1,
            ],
            16 => [
                'id' => 17,
                'title' => 'fafsahfsadfdsadfa',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-05',
                'project_id' => 2,
                'created_at' => '2025-10-05 08:52:26',
                'updated_at' => '2025-10-05 08:52:26',
                'created_by' => 1,
            ],
            17 => [
                'id' => 18,
                'title' => 'task is ad',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-05',
                'project_id' => 2,
                'created_at' => '2025-10-05 08:53:24',
                'updated_at' => '2025-10-05 08:53:24',
                'created_by' => 1,
            ],
            18 => [
                'id' => 19,
                'title' => 'this is the anoter word',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-05',
                'project_id' => 2,
                'created_at' => '2025-10-05 10:25:07',
                'updated_at' => '2025-10-05 10:25:07',
                'created_by' => 1,
            ],
            19 => [
                'id' => 20,
                'title' => 'fsdafsafsaf',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-05',
                'project_id' => 2,
                'created_at' => '2025-10-05 10:25:38',
                'updated_at' => '2025-10-05 10:25:38',
                'created_by' => 1,
            ],
            20 => [
                'id' => 21,
                'title' => 'fsdafdsaf',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-05',
                'project_id' => 2,
                'created_at' => '2025-10-05 10:42:43',
                'updated_at' => '2025-10-05 10:42:43',
                'created_by' => 1,
            ],
            21 => [
                'id' => 22,
                'title' => 'fdsafdasfdsaf',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-05',
                'project_id' => 2,
                'created_at' => '2025-10-05 10:44:12',
                'updated_at' => '2025-10-05 10:44:12',
                'created_by' => 1,
            ],
            22 => [
                'id' => 23,
                'title' => 'fsafdsafdsa',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-05',
                'project_id' => 2,
                'created_at' => '2025-10-05 10:45:14',
                'updated_at' => '2025-10-05 10:45:14',
                'created_by' => 1,
            ],
            23 => [
                'id' => 24,
                'title' => 'test',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-05',
                'project_id' => 1,
                'created_at' => '2025-10-05 10:58:03',
                'updated_at' => '2025-10-05 10:58:03',
                'created_by' => 1,
            ],
            24 => [
                'id' => 25,
                'title' => 'this is the aother thsre',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-05',
                'project_id' => 1,
                'created_at' => '2025-10-05 11:08:00',
                'updated_at' => '2025-10-05 11:08:00',
                'created_by' => 1,
            ],
            25 => [
                'id' => 26,
                'title' => 'safsdafas',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-05',
                'project_id' => 1,
                'created_at' => '2025-10-05 11:17:31',
                'updated_at' => '2025-10-05 11:17:31',
                'created_by' => 1,
            ],
            26 => [
                'id' => 27,
                'title' => 'the test is done',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-05',
                'project_id' => 1,
                'created_at' => '2025-10-05 13:40:24',
                'updated_at' => '2025-10-05 13:40:24',
                'created_by' => 1,
            ],
            27 => [
                'id' => 28,
                'title' => 'this anotther test',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-05',
                'project_id' => 1,
                'created_at' => '2025-10-05 13:42:07',
                'updated_at' => '2025-10-05 13:42:07',
                'created_by' => 1,
            ],
            28 => [
                'id' => 29,
                'title' => 'thisfasdfsafsda',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-05',
                'project_id' => 1,
                'created_at' => '2025-10-05 13:43:23',
                'updated_at' => '2025-10-05 13:43:23',
                'created_by' => 1,
            ],
            29 => [
                'id' => 30,
                'title' => 'afdasfasdfdsa',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-05',
                'project_id' => 1,
                'created_at' => '2025-10-05 13:49:21',
                'updated_at' => '2025-10-05 13:49:21',
                'created_by' => 1,
            ],
            30 => [
                'id' => 31,
                'title' => 'the problem of the is pusher is fxe d',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-05',
                'project_id' => 1,
                'created_at' => '2025-10-05 13:50:07',
                'updated_at' => '2025-10-05 13:50:07',
                'created_by' => 1,
            ],
            31 => [
                'id' => 32,
                'title' => 'fsdafdasfsda',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-05',
                'project_id' => 1,
                'created_at' => '2025-10-05 13:50:49',
                'updated_at' => '2025-10-05 13:50:49',
                'created_by' => 1,
            ],
            32 => [
                'id' => 33,
                'title' => 'fasfasfdasfsaf',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-05',
                'project_id' => 1,
                'created_at' => '2025-10-05 13:52:09',
                'updated_at' => '2025-10-05 13:52:09',
                'created_by' => 1,
            ],
            33 => [
                'id' => 34,
                'title' => 'fsadfdasfdasf',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-05',
                'project_id' => 1,
                'created_at' => '2025-10-05 13:53:09',
                'updated_at' => '2025-10-05 13:53:09',
                'created_by' => 1,
            ],
            34 => [
                'id' => 35,
                'title' => 'fsdafasfdasf',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-05',
                'project_id' => 1,
                'created_at' => '2025-10-05 13:55:04',
                'updated_at' => '2025-10-05 13:55:04',
                'created_by' => 1,
            ],
            35 => [
                'id' => 36,
                'title' => 'fdsaffsafas',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-05',
                'project_id' => 1,
                'created_at' => '2025-10-05 13:55:49',
                'updated_at' => '2025-10-05 13:55:49',
                'created_by' => 1,
            ],
            36 => [
                'id' => 37,
                'title' => 'this is the another one',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-05',
                'project_id' => 1,
                'created_at' => '2025-10-05 13:57:20',
                'updated_at' => '2025-10-05 13:57:20',
                'created_by' => 1,
            ],
            37 => [
                'id' => 38,
                'title' => 'web development project first User management Configurations  Ahmad Edris Malia @edris.malya@dab.gov.af All Tasks all pending and Completed tasks Add a new task... Pending List 21',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-05',
                'project_id' => 1,
                'created_at' => '2025-10-05 13:59:46',
                'updated_at' => '2025-10-05 13:59:46',
                'created_by' => 1,
            ],
            38 => [
                'id' => 39,
                'title' => 'this sht eafasfdasfasfdas',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-05',
                'project_id' => 1,
                'created_at' => '2025-10-05 14:08:29',
                'updated_at' => '2025-10-05 14:08:29',
                'created_by' => 1,
            ],
            39 => [
                'id' => 40,
                'title' => 'gsdfgsdgsdg',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-05',
                'project_id' => 1,
                'created_at' => '2025-10-05 14:10:37',
                'updated_at' => '2025-10-05 14:10:37',
                'created_by' => 1,
            ],
            40 => [
                'id' => 41,
                'title' => 'this the link that must',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-05',
                'project_id' => 1,
                'created_at' => '2025-10-05 14:18:12',
                'updated_at' => '2025-10-05 14:18:12',
                'created_by' => 1,
            ],
            41 => [
                'id' => 42,
                'title' => 'zarhon sha ahmad',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-05',
                'project_id' => 1,
                'created_at' => '2025-10-05 14:22:38',
                'updated_at' => '2025-10-05 14:22:38',
                'created_by' => 1,
            ],
            42 => [
                'id' => 43,
                'title' => 'just for test',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-05',
                'project_id' => 1,
                'created_at' => '2025-10-05 14:23:38',
                'updated_at' => '2025-10-05 14:23:38',
                'created_by' => 1,
            ],
            43 => [
                'id' => 44,
                'title' => 'This is for tesitng',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-06',
                'project_id' => 2,
                'created_at' => '2025-10-06 16:37:00',
                'updated_at' => '2025-10-06 16:37:00',
                'created_by' => 1,
            ],
            44 => [
                'id' => 45,
                'title' => 'Please fix this',
                'description' => null,
                'type' => 'High',
                'status' => 'completed',
                'due_to' => '2025-10-07',
                'project_id' => 2,
                'created_at' => '2025-10-06 16:37:59',
                'updated_at' => '2025-10-06 16:39:14',
                'created_by' => 1,
            ],
            45 => [
                'id' => 46,
                'title' => 'test 123',
                'description' => null,
                'type' => 'Medium',
                'status' => 'Pending',
                'due_to' => '2025-10-06',
                'project_id' => 2,
                'created_at' => '2025-10-06 16:38:39',
                'updated_at' => '2025-10-06 16:38:39',
                'created_by' => 1,
            ],
        ]);

    }
}
